### ISSUE TITLE
apply snapshot after reload

### ISSUE THREAD

**Issue by robinfehr** [Raathigesh/wiretap#1]
first of all - cool project!

feature request:
it would be actually very cool if we could apply snapshots after a reload - save snapshots/recordings and apply them even after a reload.

use case:
in a more complex app, for example, we have to execute multiple actions to reach the actual state where the feature - the one we're currently working on - can be retested.

**Comment by Raathigesh** [comment]
That's a very valid use case. I'll make sure to not to clear recordings of action during refresh. Expect this in the next release 😄

**Comment by robinfehr** [comment]
would actually also be nice if certain snapshots could be persisted generally so that they could be used even after reopening the wiretap app.

**Comment by Raathigesh** [comment]
For persisting, I can think of two approaches
- Persist it globally but if you are switching between projects this could be trouble.
- Allow users to export recordings and snapshots as JSON and then re-import it. Wiretap won't persist in this case.
