### ISSUE TITLE
Make host configurable

### ISSUE THREAD

**Issue by srigi** [Raathigesh/wiretap#10]
I'm running my mobx app in Docker. By looking at the [source](https://github.com/Raathigesh/wiretap/blob/490348d134dd49a5d327cfb86510c3aa52ec4e17/packages/lib/src/walkieTalkie.js#L5) I can see that the host is hardcoded. `localhost` is not usable if app is running in docker container.

Please add `host` option to configuration.

**Comment by Raathigesh** [comment]
I'll include it as a configuration option 👍

_Sent from my LGE Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Raathigesh** [comment]
Released with Mobx-wiretap 0.13.0. Readme has been updated accordingly. let me know if you run into any issues.

**Comment by srigi** [comment]
@Raathigesh Hi, thanks, works like a charm.

There is a typo in Readme:

```js
wiretap("My awesome app", {
    host: 'http://localhost'.
    port: 84585
});
```

There should be comma, not dot at the end of the second row.

**Comment by Raathigesh** [comment]
That's nice to hear!

Oh yea! Fixed it! Thanks for pointing it out.
